### Auth Test
GET http://localhost:8000/auth-test
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydmNhRk1abHhSdldCUjNuZlRMSGx2MVg4MjIiLCJ0eXAiOiJKV1QifQ.eyJlbWFpbCI6ImFnbmlldmU3MEBnbWFpbC5jb20iLCJleHAiOjE3NDQ0NzIwMDUsImZ2YSI6WzIyMCwtMV0sImlhdCI6MTc0NDQ3MTk0NSwiaXNzIjoiaHR0cHM6Ly9idXJzdGluZy1nbnUtMzMuY2xlcmsuYWNjb3VudHMuZGV2IiwianRpIjoiZjdkNzljYmI3ZjI2OTY3ZTAyOTEiLCJsYXN0X3NpZ25faW5fYXQiOjE3NDQ0NTg3MDQsIm5iZiI6MTc0NDQ3MTkzNSwic2lkIjoic2Vzc18ydmN5WVpqcXJzODJDVk8ydnpNMEhaZkpqanciLCJzdWIiOiJ1c2VyXzJ2Y3RqeFF5d1VvSHdZNVRIbkl4U0xQUGtVaCIsInVzZXJfaWQiOiJ1c2VyXzJ2Y3RqeFF5d1VvSHdZNVRIbkl4U0xQUGtVaCJ9.YV8sWBrTqEdJ6vSkvHRuiJ1ejhnGSuEP07h_TyfMxzd4iJki14M4FFlOSt1PMHQO992IGXyz5U8wR5TO2QGqXCim731OBGJZGVw4jz0ZvOgeyJLnGZIBJSAF5JgHmKcFBrli--4V5LIlnEXh1FQvVnz5voLAiQJ5Sk22E7__wWI0i5CXNWdeKpyFuhJGqHOI1puqFUxRpe79-RWBnB1odYeSvvMZ5fW7jWb07Rp_AhbGfgTWiRTowcf_rzFR_QqHS9WEso4v9vXtu9dWM-OvU8WG-8glmSqE17zk4AHP5NLmeNnbrf2LUO-hrxse9HwiaHx89-nHcvlvIfdaViZAQg

### Upload PDF
POST http://localhost:8000/upload_pdf/
Authorization: Bearer 
Content-Type: multipart/form-data

### Chat Endpoint
POST http://0.0.0.0:8000/chat/
# POST https://b88g8kk0k0owcgw08ocgg8gk.coolify.agnieve.com/chat/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydmNhRk1abHhSdldCUjNuZlRMSGx2MVg4MjIiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJlbWFpbCI6ImFnbmlldmU3MEBnbWFpbC5jb20iLCJleHAiOjE3NDQ4ODU2MDYsImZ2YSI6WzI3NjIsLTFdLCJpYXQiOjE3NDQ4ODU1NDYsImlzcyI6Imh0dHBzOi8vYnVyc3RpbmctZ251LTMzLmNsZXJrLmFjY291bnRzLmRldiIsImp0aSI6IjhhODgyMzc3ZDQ0MDViZjkzNzVmIiwibGFzdF9zaWduX2luX2F0IjoxNzQ0NzMzNDg0LCJuYmYiOjE3NDQ4ODU1MzYsInNpZCI6InNlc3NfMnZsVmlvb2Q2WW9LdlNjc1kxR09neVBFNmpEIiwic3ViIjoidXNlcl8ydmN0anhReXdVb0h3WTVUSG5JeFNMUFBrVWgiLCJ1c2VyX2lkIjoidXNlcl8ydmN0anhReXdVb0h3WTVUSG5JeFNMUFBrVWgifQ.bp8d8uhKBVeWu3aUz3oFcBu7VAkyE1514P5ggUuAEaScpmamqR6vGFz3LMjY5wS9FrZ5UWc6LVw70lEl-17F2kS1RI6O0aBfLhMldOKKRxR2uFt9l7G3y9zxMuyPf_mk3Qtgk1zlG7nGCjdqRAxQSb9TZGBSeUGjViLLduMK19Q1WMB-3LHlhLjmjPhQ6A9ByD4eVCDMH7ZTAeP6BfP30XZeqEZCnPhrS4-avi8Mt3IFDsWhBBSlJ7sz_JVABllQDw9_bU58fpw7WKwH9KZG5LHHOwi8YiipQ5_UJGjN7u_FbQSxqytC6o4yPS7qnetgMAJDFml3nAwOn19XKXpBcw
Content-Type: application/json

{
  "query": "Hi, I'm a bit tired right now."
}

# {
#   "query": "I'm a bit tired",
#   "session_id": "session_id can leave empty for new chat"
# }

### Get User Chat Sessions
GET https://b88g8kk0k0owcgw08ocgg8gk.coolify.agnieve.com/chat_sessions/
Authorization: Bearer TOKEN_FROM_AUTH_ENDPOINT

### Update Chat Session Title
PUT http://localhost:3005/chat_sessions/1/title
Content-Type: application/json
Authorization: Bearer YOUR_TOKEN_HERE

{
    "title": "New Session Title"
}

### Delete Chat Session
DELETE http://localhost:3005/chat_sessions/1
Authorization: Bearer YOUR_TOKEN_HERE

### Create Meditation
POST http://localhost:8000/meditations/
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
  "title": "Morning Calm",
  "description": "A meditation for a calm start to your day.",
  "category": "Mindfulness",
  "tags": ["morning", "calm"],
  "script": "Sit comfortably and focus on your breath...",
  "image_url": "https://example.com/image.jpg",
  "audio_url": "https://example.com/audio.mp3"
}

### Get All Meditations
GET http://localhost:8000/meditations/
Authorization: Bearer YOUR_TOKEN_HERE

### Get Meditation by ID
GET http://localhost:8000/meditations/1
Authorization: Bearer YOUR_TOKEN_HERE

### Update Meditation
PUT http://localhost:8000/meditations/1
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
  "title": "Updated Meditation Title",
  "description": "Updated description.",
  "category": "Relaxation",
  "tags": ["evening", "relax"],
  "script": "Updated script...",
  "image_url": "https://example.com/new-image.jpg",
  "audio_url": "https://example.com/new-audio.mp3"
}

### Delete Meditation
DELETE http://localhost:8000/meditations/1
Authorization: Bearer YOUR_TOKEN_HERE