### Auth Test
GET http://localhost:8000/auth-test
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydmNhRk1abHhSdldCUjNuZlRMSGx2MVg4MjIiLCJ0eXAiOiJKV1QifQ.eyJlbWFpbCI6ImFnbmlldmU3MEBnbWFpbC5jb20iLCJleHAiOjE3NDQ0NzIwMDUsImZ2YSI6WzIyMCwtMV0sImlhdCI6MTc0NDQ3MTk0NSwiaXNzIjoiaHR0cHM6Ly9idXJzdGluZy1nbnUtMzMuY2xlcmsuYWNjb3VudHMuZGV2IiwianRpIjoiZjdkNzljYmI3ZjI2OTY3ZTAyOTEiLCJsYXN0X3NpZ25faW5fYXQiOjE3NDQ0NTg3MDQsIm5iZiI6MTc0NDQ3MTkzNSwic2lkIjoic2Vzc18ydmN5WVpqcXJzODJDVk8ydnpNMEhaZkpqanciLCJzdWIiOiJ1c2VyXzJ2Y3RqeFF5d1VvSHdZNVRIbkl4U0xQUGtVaCIsInVzZXJfaWQiOiJ1c2VyXzJ2Y3RqeFF5d1VvSHdZNVRIbkl4U0xQUGtVaCJ9.YV8sWBrTqEdJ6vSkvHRuiJ1ejhnGSuEP07h_TyfMxzd4iJki14M4FFlOSt1PMHQO992IGXyz5U8wR5TO2QGqXCim731OBGJZGVw4jz0ZvOgeyJLnGZIBJSAF5JgHmKcFBrli--4V5LIlnEXh1FQvVnz5voLAiQJ5Sk22E7__wWI0i5CXNWdeKpyFuhJGqHOI1puqFUxRpe79-RWBnB1odYeSvvMZ5fW7jWb07Rp_AhbGfgTWiRTowcf_rzFR_QqHS9WEso4v9vXtu9dWM-OvU8WG-8glmSqE17zk4AHP5NLmeNnbrf2LUO-hrxse9HwiaHx89-nHcvlvIfdaViZAQg

### Upload PDF
POST http://localhost:8000/upload_pdf/
Authorization: Bearer 
Content-Type: multipart/form-data

### Chat Endpoint
POST https://b88g8kk0k0owcgw08ocgg8gk.coolify.agnieve.com/chat/
Authorization: Bearer TOKEN_FROM_AUTH_ENDPOINT
Content-Type: application/json

{
  "query": "How does photosynthesis work?",
  "session_id": "session_id can leave empty for new chat"
}

### Get User Chat Sessions
GET https://b88g8kk0k0owcgw08ocgg8gk.coolify.agnieve.com/chat_sessions/
Authorization: Bearer TOKEN_FROM_AUTH_ENDPOINT

### Update Chat Session Title
PUT http://localhost:3005/chat_sessions/1/title
Content-Type: application/json
Authorization: Bearer YOUR_TOKEN_HERE

{
    "title": "New Session Title"
}

### Delete Chat Session
DELETE http://localhost:3005/chat_sessions/1
Authorization: Bearer YOUR_TOKEN_HERE